import type { Sandbox } from "@e2b/code-interpreter";
import type { E2BArtifact } from "lib/code-runner/code-runner.interface";
import logger from "lib/logger";
import { errorLabel } from "./create-sandbox";

/**
 * Collection of files generated by sandbox code execution.
 *
 * Code run in the E2B code-interpreter writes files (PDFs, CSVs, images, …)
 * to its working directory. After execution we diff the directory listing
 * against a pre-run snapshot and return the new/changed files as downloadable
 * artifacts.
 */

/** Working directory of the code-interpreter template (user `user`). */
export const SANDBOX_WORKDIR = "/home/user";

/** Per-file size cap for returned artifacts. */
export const MAX_ARTIFACT_FILE_BYTES = 8 * 1024 * 1024;
/** Total size budget across all artifacts of one execution. */
export const MAX_ARTIFACT_TOTAL_BYTES = 16 * 1024 * 1024;

const MIME_BY_EXTENSION: Record<string, string> = {
  pdf: "application/pdf",
  csv: "text/csv",
  tsv: "text/tab-separated-values",
  json: "application/json",
  txt: "text/plain",
  md: "text/markdown",
  html: "text/html",
  xml: "application/xml",
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  gif: "image/gif",
  svg: "image/svg+xml",
  webp: "image/webp",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  xls: "application/vnd.ms-excel",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  zip: "application/zip",
  mp4: "video/mp4",
  mp3: "audio/mpeg",
  wav: "audio/wav",
};

export function mimeTypeForFile(filename: string): string {
  const ext = filename.split(".").pop()?.toLowerCase() ?? "";
  return MIME_BY_EXTENSION[ext] ?? "application/octet-stream";
}

/** Minimal shape of an SDK directory entry we care about. */
export interface ListedFile {
  name: string;
  path: string;
  type?: string;
  size: number;
}

/** Snapshot a directory listing as path → size (files only). */
export function snapshotListing(entries: ListedFile[]): Map<string, number> {
  const map = new Map<string, number>();
  for (const entry of entries) {
    if (entry.type === "file") map.set(entry.path, entry.size);
  }
  return map;
}

/**
 * Files that appeared or changed size since the pre-run snapshot.
 * Hidden files and empty files are skipped; size caps are enforced (and
 * logged) by the collector.
 */
export function findGeneratedFiles(
  before: Map<string, number>,
  after: ListedFile[],
): ListedFile[] {
  return after.filter((entry) => {
    if (entry.type !== "file") return false;
    if (entry.name.startsWith(".")) return false;
    if (entry.size <= 0) return false;
    const previousSize = before.get(entry.path);
    return previousSize === undefined || previousSize !== entry.size;
  });
}

/**
 * Diff the sandbox working directory against `before` and read the generated
 * files as base64 artifacts. Best-effort: any failure returns what was
 * collected so far — file collection must never fail the execution itself.
 */
export async function collectGeneratedFiles(
  sbx: Sandbox,
  before: Map<string, number>,
): Promise<E2BArtifact[]> {
  const artifacts: E2BArtifact[] = [];
  try {
    const after = await sbx.files.list(SANDBOX_WORKDIR);
    const generated = findGeneratedFiles(before, after);
    let totalBytes = 0;

    for (const file of generated) {
      if (file.size > MAX_ARTIFACT_FILE_BYTES) {
        logger.warn(
          `[e2b] artifact skipped (file too large) file=${file.name} size=${file.size}`,
        );
        continue;
      }
      if (totalBytes + file.size > MAX_ARTIFACT_TOTAL_BYTES) {
        logger.warn(
          `[e2b] artifact skipped (total size budget) file=${file.name} size=${file.size}`,
        );
        continue;
      }
      const bytes = await sbx.files.read(file.path, { format: "bytes" });
      totalBytes += bytes.byteLength;
      artifacts.push({
        filename: file.name,
        mimeType: mimeTypeForFile(file.name),
        contentBase64: Buffer.from(bytes).toString("base64"),
      });
    }
  } catch (err) {
    logger.warn(`[e2b] artifact collection failed error=${errorLabel(err)}`);
  }
  return artifacts;
}

/** Best-effort pre-run snapshot of the working directory. */
export async function snapshotWorkdir(
  sbx: Sandbox,
): Promise<Map<string, number>> {
  try {
    return snapshotListing(await sbx.files.list(SANDBOX_WORKDIR));
  } catch {
    return new Map();
  }
}
