import { withAuth } from "auth/route-guard";
import { FileNotFoundError } from "lib/errors";
import { serverFileStorage } from "lib/file-storage";
import {
  downloadFilenameFromKey,
  getContentTypeFromFilename,
} from "lib/file-storage/storage-utils";
import logger from "lib/logger";
import { NextResponse } from "next/server";

export const maxDuration = 60;

/**
 * Durable, authenticated download for files in private storage buckets
 * (e.g. artifacts generated by sandbox code execution). The server streams
 * the object via the service role, so the link never expires and the bucket
 * never needs to be public.
 *
 * GET /api/storage/download?key=<userId>/<uuid>-<filename>
 */
export const GET = withAuth(async (req: Request, session) => {
  const key = new URL(req.url).searchParams.get("key");
  if (!key || key.includes("..")) {
    return NextResponse.json(
      { error: "A valid storage key is required" },
      { status: 400 },
    );
  }

  // Keys are namespaced by owner; only the owner may download.
  if (!key.startsWith(`${session.user.id}/`)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  try {
    const buffer = await serverFileStorage.download(key);
    const filename = downloadFilenameFromKey(key);
    return new Response(new Uint8Array(buffer), {
      headers: {
        "Content-Type": getContentTypeFromFilename(filename),
        "Content-Disposition": `attachment; filename="${filename.replaceAll('"', "")}"`,
        "Content-Length": String(buffer.byteLength),
      },
    });
  } catch (err) {
    if (err instanceof FileNotFoundError) {
      return NextResponse.json({ error: "File not found" }, { status: 404 });
    }
    logger.error(`[storage] download failed key=${key}`, err);
    return NextResponse.json({ error: "Download failed" }, { status: 500 });
  }
});
